# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ZYMIN
subtitle: 生活 | 学习 | 科研 | 育儿
description: 一个专注知识分享的网站
keywords: 知识分享, 生活技能, 科研技巧, 学习资源, 育儿教育, 娱乐资源
author: ZYMIN
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zymin.cn/
root: /
permalink: arcticle/:id.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
    科研: research
    生活: life
    育儿: baby
    论文: paper
    资源: resource
    数学: math
    软件: software
    视觉: vision
    网站: website
    科普: popular-science
    控制: control
    申请: application
    文献: literature
    趋势: trend
    教程: course
    词汇: word
    句型: sentence
    辅食: babyfood
    教育: education
    汽车: car
    食品: food
    学习: study
    妙招: tips
    健康: health
    
tag_map:
    科研: research
    生活: life
    育儿: baby
    论文: paper
    资源: resource
    数学: math
    软件: software
    视觉: vision
    网站: website
    科普: popular-science
    控制: control
    申请: application
    文献: literature
    前沿: trend
    教程: course
    词汇: word
    句型: sentence
    辅食: babyfood
    教育: education
    汽车: car
    衣服: clothing
    食品: food
    学习: study
    妙招: tips
    健康: health
    总结: summary
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x

# 链接提交
baidu_url_submit:
  count: 10 ##提交最新的一个链接
  host: zymin.cn ##在百度站长平台中注册的域名
  token: 3Rul6QlQHshC2eXR ##请注意这是您的秘钥，所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt  ##文本文档的地址， 新链接会保存在此文本文档里
  xz_appid: 1596800714983061 ## 你的熊掌号 appid
  xz_token: ftg25QytyVx1xIe2 ## 你的熊掌号 token
  xz_count: 10 ## 从所有的提交的数据当中选取最新的10条,该数量跟你的熊掌号而定
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: 
    github: git@github.com:zzhm/zzhm.github.io.git,master
    #coding: git@git.coding.net:zzhm/zzhm.git,master
    coding: git@git.dev.tencent.com:zzhm/zzhm.git,master
- type: baidu_url_submitter ## 这是新加的
- type: baidu_xz_url_submitter # 百度熊掌号

# ---------------------------------------------------------------
# Theme configurations
# ---------------------------------------------------------------
#style: material    # 导航栏和标题栏背景是主题色
style: pure        # 导航栏和标题栏背景是白色
# 导航栏  ok
nav_menu:
  - name: 主页
   # icon: fas fa-home
    url:  /
  - name: 生活
   # icon: fas fa-rss
    url:  categories/life/
  - name: 学习
   # icon: fas fa-book
    url: categories/study/
  - name: 科研
   # icon: fas fa-graduation-cap
    url: categories/research/ 
  - name: 育儿
 #   icon: fas fa-baby
    url:  categories/baby/
  - name: 导航
  #  icon: fas fa-location-arrow
    url:  navigation/
  - name: 友链
  #  icon: fas fa-location-arrow
    url:  friends/
  - name: 归档
   # icon: fas fa-archive
    url: archives/
  - name: 关于
  #  icon: fas fa-user
    url: about/

# 侧栏插件
widgets:
  - widget: author
    avatar: images/avatar.gif
    jinrishici: true
    title: 
    body: 
    social: true
  
  - widget: plain
    enable: false
    icon: fas fa-bullhorn
    title: 欢迎访问本站
    body: '本站备用网址:https://blog.zymin.cn'
    more:
      icon: fas fa-question-circle
      url:  about/
  
  - widget: toc
    icon: fas fa-list
    title: "目录"
  
  - widget: list
    enable: false
    icon: fas fa-medal
    title: 精选项目
    more:
      icon: fas fa-arrow-right
      url: https://xaoxuu.com/projects/
    rows:
      - name: AXKit
        desc: iOS开源库
        icon: fas fa-cube
        url: https://xaoxuu.com/wiki/axkit/
  
  - widget: category
    enable: false
    icon: fas fa-folder-open
    title: "博文分类"
  
  - widget: tagcloud
    icon: fas fa-fire
    title: "热门话题"
  
  - widget: music
    icon: fas fa-compact-disc
    title: "最近在听"
    more:
      icon: far fa-heart
      url: https://music.163.com/#/user/home?id=1546778263
    color: '#3DC550'  # 主题色
    volume: 0.5       # 默认音量大小（0~1之间）
    mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 2352766871    # 歌曲/专辑/歌单 ID

  - widget: list
    icon: fas fa-link
    title: 特别链接
    rows:
      - name: 优惠信息|省钱助手
        icon: fas fa-shopping-cart
        url: http://www.shihuidaren.cn/
      - name: 科袖发现|科研教程
        icon: fas fa-graduation-cap
        url: http://www.ekexiu.com/discover.html
      - name: 谷歌镜像|文献下载
        icon: fas fa-file
        url: https://ab.waguge.com/           
      - name: 儿科学会|权威育儿
        icon: fas fa-baby
        url: https://www.aap.org/en-us/Pages/Default.aspx   
      - name: 专利下载|
        icon: fas fa-download
        url: http://www.drugfuture.com/cnpat/cn_patent.asp      
      - name: 英语书籍|研究必备
        icon: fas fa-book
        url: http://gen.lib.rus.ec/          
  


# 页脚社交信息  ok
social:
  - icon: fas fa-envelope
    url: mailto:1808525162@qq.com
  - icon: fas fa-rss
    url: atom.xml
  - icon: fas fa-music
    url: https://music.163.com/#/user/home?id=1546778263

# 推荐文章
# recommended_posts:
  # autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  # server: https://api.truelaurel.com # 后端推荐服务器地址
  # timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  # excludePattern: []
  # titleHtml: <h4>推荐文章</h4> #自定义标题
  # internalLinks: 5 # 内部文章数量
  # externalLinks: 0 # 外部文章数量
  # fixedNumber: false
  
# 百度统计key
#baidu_analytics_key: 4aa86941ec5081fad9df5db06100091b 
sitemap:
    path: sitemap.xml
    tag: false
    category: false
# valine
valine:
  enable: true  # 如果你想用Valine评论系统，请设置enable为true
  app_id: yful60yYmA2c5TtXIETywL2a-gzGzoHsz # 必填
  app_key: Jzc4LfsMLg0jmm9ymfL9MH2j # 必填
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn

# 分享
share:
  - id: qq
    name: QQ好友
    img: ../images/qq.png
  - id: qzone
    name: QQ空间
    img: ../images/qqz.png
  - id: qrcode
    name: 微信
    img: ../images/vx.png
  - id: weibo
    name: 微博
    img: ../images/vb.png
  - id: youdao
    name: 有道
    img: ../images/yd.png
  - id: qrcode
    name: QRcode
    img: ../images/qrcode.png

# Search
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less
less:
  compress: true
